### ISSUE TITLE
Try music-metadata

### ISSUE THREAD

**Issue by Borewit** [chris-shaw-2011/mp3-to-aac#1]
Hi Chris, have you considered using [music-metadata](https://github.com/Borewit/music-metadata) for your project?

**Comment by chris-shaw-2011** [comment]
I will look into it

**Comment by Borewit** [comment]
Cool, let me know if you need any help.

**Comment by chris-shaw-2011** [comment]
Changed my tests over to use music-metadata and it simplified some of the code
